### PR TITLE
Update Localizable.strings

### PR DESCRIPTION
**Pull request by bjinse**
Missing: 
ago = geleden
Second = Seconde
Seconds = Seconden
Minute = Minuut
Minutes = Minuten
Hour = Uur
Hours = Uren
Run in terminal... should be without ellipses (it runs direct, without dialog). Same for "Open plugin folder..."

### CODE REVIEW

**Comment by melonamin** [comment]
Time is handled by iOS, it should be localized automatically 

As for ellipses - I was trying to find something in HIG about it, but couldn't. You're saying if there is no dialog than no ellipses? What is a "dialog" in this context? "Preferences..." should be with ellipses but it presents a "window" not a "dialog", I'm confused.

**Comment by bjinse** [comment]
I remember this from the early days. I actually have "Inside Macintosh" volumes 1 to 5 laying around.... 
Current documentation:
https://developer.apple.com/design/human-interface-guidelines/macos/menus/menu-anatomy/
Which states:
Use an ellipsis whenever choosing a menu item requires additional input from the user. The ellipsis character (…) means a dialog or separate window will open and prompt the user for additional information or to make a choice.
I will look into the time thing. I have an export LANG in the .sh file that does setup for and then calls the python script

**Comment by melonamin** [comment]
>https://developer.apple.com/design/human-interface-guidelines/macos/menus/menu-anatomy/

Perfect, thanks 

This how it looks in Dutch locale:

Screen Shot 2020-12-24 at 10 10 42 AM

**Comment by bjinse** [comment]
Is there anything I should do, or was making the pr all I needed to do? When you need more translations as you add more strings in the future, please mail me!

**Comment by melonamin** [comment]
No, all good. Thank you!

**Comment by bjinse** [comment]
Do you need new Dutch translations for the latest version?

**Comment by melonamin** [comment]
Hi @bjinse,

Yes and No. I don't have localization support in the latest UI changes, I would need to add it before I can use your help.

I'll ping you. Thank you.

**Pull request merged**
